# Generated by Django 3.2.6 on 2021-09-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(max_length=32)),
                ('laptop_Manufacturer', models.CharField(max_length=32)),
                ('RAM', models.IntegerField()),
                ('ROM', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('processor', models.CharField(max_length=32)),
                ('price', models.FloatField()),
            ],
        ),
    ]
